id: A86EE2587
title: A Vajrakīla Lineage Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.582730
  last_modified_at: 2022-03-01 01:45:14.582737
