id: A86EE2587
title: The Guru Yoga of the Profound Path
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.594636
  last_modified_at: 2022-03-01 01:45:14.594639
