id: A86EE2587
title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.593579
  last_modified_at: 2022-03-01 01:45:14.593581
