id: A86EE2587
title: Guru Yoga
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.587985
  last_modified_at: 2022-03-01 01:45:14.587988
