id: A86EE2587
title: Serkyem (Golden Libation) Offering to the Guardians of the Tradition
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.591507
  last_modified_at: 2022-03-01 01:45:14.591510
