id: A86EE2587
title: The Twenty-Eight Commitments
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.608400
  last_modified_at: 2022-03-01 01:45:14.608403
