id: A86EE2587
title: The Seeds of Faith, A Prayer to the Vidyādhara and Great Tertön Lerab Lingpa
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.600958
  last_modified_at: 2022-03-01 01:45:14.600962
