id: A86EE2587
title: Prayer for the Flourishing of the Teachings
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.589798
  last_modified_at: 2022-03-01 01:45:14.589801
