id: A86EE2587
title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
  Light'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.605864
  last_modified_at: 2022-03-01 01:45:14.605867
