id: A86EE2587
title: The Wisdom Mind Practice of One Kīla
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.611729
  last_modified_at: 2022-03-01 01:45:14.611731
