id: A86EE2587
title: 'The Sweet Song of Māra''s Defeat: A Prayer for the Long Life of the Great
  Tertön and Vidyādhara Lerab Lingpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.604107
  last_modified_at: 2022-03-01 01:45:14.604110
