id: A86EE2587
title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the Sixty
  Solitary Forms of Yamāntaka
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.596687
  last_modified_at: 2022-03-01 01:45:14.596689
