id: A86EE2587
title: Brief Prayer for Pacifying the Turmoil of the Mamos
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:45:14.585654
  last_modified_at: 2022-03-01 01:45:14.585659
